# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://loboto51.github.io/lobotourisme/"  # Include trailing slash
title = "Lobotourisme"
author = "Loboto"
#copyright = "Aucun copyright."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"

DefaultContentLanguage = "fr"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
