languageCode: "fr-FR"
defaultContentLanguage: "fr"
baseUrl: "https://loboto51.github.io/lobotourisme/"
title: "Lobotourisme"
theme: "anubis"
paginate: 10
disqusShortname: ""
googleAnalytics: ""
enableRobotsTXT: true
enableGitInfo: true

menu:
  main:
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 2

  - identifier: photo
    name: Photo
    title: Photo
    url: /categories/photo/
    weight: 3

  - identifier: dev
    name: Dev
    title: Dev
    url: /categories/dev/
    weight: 4
    
  - identifier: ecologie
    name: Ecologie
    title: Ecologie
    url: /categories/ecologie/
    weight: 5

  - identifier: moto
    name: Moto
    title: Moto
    url: /categories/moto/
    weight: 6

  - identifier: apropos
    name: A propos
    title: A propos
    url: /about/
    weight: 7

params:
  author: "Loboto"
  email: mail@example.org # used for microformats
  avatar: "/images/me.png" # used for microformats
  description: ""
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "02/01/2006"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: true # show read more button
  readNextPosts: 5  # show 5 related posts, 0 by default
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  # utteranc.es support
  utterancesRepo: "loboto51/lobotourisme"  # mandatory
  utterancesTheme: "boxy-light" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  social:
  - id: github
    name: loboto51
    url: "https://github.com/loboto51/"
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
